const AuthActionTypes={
    SIGNIN_START:"SIGNIN_START",
    SIGNIN_SUCCESSFUL:"SIGNIN_SUCCESSFUL",
    SIGNIN_FAILURE:"SIGNIN_FAILURE",
    SIGNUP_START:"SIGNUP_START",
    SIGNUP_SUCCESSFUL:"SIGNUP_SUCCESSFUL",
    SIGNUP_FAILURE:"SIGNUP_FAILURE",
    LOGOUT_START:"LOGOUT_START",
    LOGOUT_SUCCESSFUL:"LOGOUT_SUCCESSFUL",
    LOGOUT_FAILURE:"LOGOUT_FAILURE"
}

export default AuthActionTypes