get http://localhost:1337/register

###
post http://localhost:1337/register
Content-Type: application/json

{
    "username": "harsha",
    "password": "harsha123",
    "email_id": "harshamakham"
}

###
post http://localhost:1337/login
Content-Type: application/json
Cookie: __AT__=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDMyNjAyMjMsImV4cCI6MTY0MzI2MDgyMywiaXNzIjoiMjJ5YXJkcyJ9.yCgmfmcsVFVIUbApYstACELc_zMR-5QegUUy5d7uprA; Max-Age=0; Path=/; Expires=Thu, 27 Jan 2022 05:10:23 GMT; HttpOnly; SameSite=Strict,__RT__=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDMyNjAyMjMsImV4cCI6MTY0MzM0NjYyMywiaXNzIjoiMjJ5YXJkcyJ9.5DHtQTvlqF1A1N0-WBOxwUuTv94jMh05LS1CjV5mzeo; Max-Age=86; Path=/; Expires=Thu, 27 Jan 2022 05:11:49 GMT; HttpOnly; SameSite=Strict

{
    "username":"parthiv",
    "password":"parthiv123"
}

###
post http://localhost:1337/feed
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhcnRoaXYiLCJwYXNzd29yZCI6InBhcnRoaXYxMjMiLCJpYXQiOjE2NDI1ODk3OTd9.vDu6qQg76dvY2tqeeeNuOUS38-18oM7vEnr8z_irPzA",
    "content":"England's umpteenth batting collapse in Hobart and their meek concession of the series also kind of left their victors a little unsure of their own supremacy"
}

###
get http://localhost:1337/feed

###
post http://localhost:1337/like
